### ISSUE TITLE
Burst + AndroidTestCase support

### ISSUE THREAD

**Issue by Kisty** [square/burst#47]
Can't seem to run Burst with AndroidTestCase using a basic custom instrumentation runner (class with getAndroidTestRunner() which returns BurstAndroid).

Using burst-android 1.0.2

01-08 07:37:52.376    2546-2546/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: uk.co.imagitech.citb.operatives.plus, PID: 2546
    java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{uk.co.imagitech.citb.operatives.plus.test/uk.co.imagitech.citb.operatives.plus.test.BurstTestRunner}: java.lang.RuntimeException: java.lang.IllegalStateException: junit.framework.TestSuite$1 requires at least 1 public constructor
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4338)
            at android.app.ActivityThread.access$1500(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: junit.framework.TestSuite$1 requires at least 1 public constructor
            at com.squareup.burst.BurstAndroid.setTest(BurstAndroid.java:38)
            at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:379)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4335)
            at android.app.ActivityThread.access$1500(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: junit.framework.TestSuite$1 requires at least 1 public constructor
            at com.squareup.burst.BurstableConstructor.findSingle(BurstableConstructor.java:24)
            at com.squareup.burst.BurstAndroid.explodeSuite(BurstAndroid.java:97)
            at com.squareup.burst.BurstAndroid.explodeSuite(BurstAndroid.java:121)
            at com.squareup.burst.BurstAndroid.setTest(BurstAndroid.java:36)
            at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:379)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4335)
            at android.app.ActivityThread.access$1500(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Do you have a public constructor?

**Comment by dlubarov** [comment]
I saw this a couple times... `junit.framework.TestSuite$1` is a dummy TestCase representing a warning. Can you put a breakpoint in that `warning` method to see what the message was?

**Comment by dlubarov** [comment]
We've dropped JUnit 3 support making this obsolete
